### PR TITLE
ToS update

### PR DESCRIPTION
**Pull request by Stanislaw-bnk**

### CODE REVIEW

**Comment by Stanislaw-bnk** [comment]
It seems there is a `merge conflict`, but I've run pre-commit on develop and it seems good:
Screenshot from 2024-05-17 11-50-46

**Comment by pietrushnic** [comment]
@Stanislaw-bnk you will not see merge conflicts locally only when you trying to merge. It seems to me that some massive formatting of menus.toml was introduced to your changes, and now there is a big merge conflict.

**Comment by Stanislaw-bnk** [comment]
@Asiderr Could you please help resolve this merge conflict? I am not sure how to fix it.

**Comment by Stanislaw-bnk** [comment]
> you have to rebase those changes on top of the most recent one, then ask @gosiastyba for confirmation for this PR.

@gosiastyba Could you please confirm that these changes in ToS from this PR are valid?

**Comment by Stanislaw-bnk** [comment]
@gosiastyba ping

**Pull request merged**
