### PR TITLE
contact: change links to nextcloud and improve contact process

### PR DESCRIPTION
**Pull request by pietrushnic**

### CODE REVIEW

**Comment by artur-rs** [comment]
@pietrushnic Coop changes look good. Please add the same code here as well: https://github.com/3mdeb/3mdeb-website/blob/main/content/_index.md?plain=1#L39 to sync main page.

**Comment by pietrushnic** [comment]
@artur-rs added 089d70fe9115

**Review by artur-rs — APPROVED** [review]

**Comment by artur-rs** [comment]
@pietrushnic base branch should be rebased. Changed to `develop` in the PR.

**Comment by pietrushnic** [comment]
@artur-rs too late

**Comment by pietrushnic** [comment]
or maybe not

**Pull request merged**
