### PR TITLE
careers.en.md: add-job

### PR DESCRIPTION
**Pull request by Stanislaw-bnk**

### CODE REVIEW

**Comment by Stanislaw-bnk** [comment]
@artur-rs Link has been fixed in this MR: https://github.com/3mdeb/3mdeb-website/pull/88
The `pre-commit.ci - pr` is a codespell failure, that can be ignored.

**Comment by macpijan** [comment]
> The pre-commit.ci - pr is a codespell failure, that can be ignored.

It must be ignored then in pre-commit config - either as a whole file, or as a specific line.

Do we have to mix Polish and English in a one file?

**Comment by Stanislaw-bnk** [comment]
> It must be ignored then in pre-commit config - either as a whole file, or as a specific line.
Do we have to mix Polish and English in a one file?

Fixed in newest commit

**Comment by Stanislaw-bnk** [comment]
@Asiderr There is an error in linkchecker here, stating `Failed: Network error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921: (certificate has expired)`. Not sure what to do with it, can you please look at it?

**Comment by Asiderr** [comment]
@Stanislaw-bnk add this page to https://github.com/3mdeb/3mdeb-website/blob/main/.lycheeignore

**Comment by Stanislaw-bnk** [comment]
Added link to https://github.com/3mdeb/3mdeb-website/blob/main/.lycheeignore, re-run the failed jobs, and the result is still the same. Are there more steps to this?

**Comment by Stanislaw-bnk** [comment]
@artur-rs @Asiderr ping2 ^

**Review by Asiderr — APPROVED** [review]

**Pull request merged**
